SQL Server start wait now exits with an error if it times out

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -57,9 +57,10 @@ jobs:
             choco install sql-server-express --no-progress
         fi
 
-        for i in {1..10}
-        do
-            echo "Waiting for SQL Server to start. Attempt $i/10."
+        maxTryCount=2
+        
+        for i in $(seq 1 $maxTryCount); do
+            echo "Waiting for SQL Server to start. Attempt $i/$maxTryCount."
 
             sqlServerIsStarted=false
             
@@ -77,8 +78,13 @@ jobs:
                 echo "SQL Server is successfully started."
                 break
             else
-                echo "SQL Server is not ready. Waiting for 1s."
-                sleep 1
+                if [ $i != $maxTryCount ]; then
+                    echo "SQL Server is not ready. Waiting for 1s."
+                    sleep 1
+                else
+                    echo "SQL Server couldn't be started."
+                    exit 1;
+                fi
             fi
         done
     - name: Set up Azurite via NPM
