Add comments to yml.

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -31,14 +31,28 @@ jobs:
         docker pull mcr.microsoft.com/azure-storage/azurite &&
         docker run --name azurite -d -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --blobPort 10000
     - name: Tests
+      # This step gets the list of all projects, selects the test projects (excluding the two test libraries) and then
+      # uses sed to create an inline bash script. What this script does:
+      # - Uses 'dotnet test -c Release --no-restore --no-build' to start up each project.
+      # - Before the test outputs '::group::project name' and after outputs '::endgroup::'. This tells GitHub that the
+      #   outputs should be placed into a collapsible region on the Actions web UI.
+      # - Each call is connected with '&&', so it stops on the first test failure to save computational resources
+      #
+      # The script is evaluated by bash and the output is passed through grep to filter out some IPv6 related garbage
+      # data produced by chromedriver. The trouble is, this way the final error code will be grep's and not the test
+      # run's, so to get around this 'SUCCESS' or 'FAILURE' is written into the .ui_test_result file before the output
+      # is sent to grep. The final line sets the result according to what was written into the .ui_test_result file.
       run: |
         export LOMBIQ_UI_TESTING_TOOLBOX_SHARED_TEST_CONFIGURATION="$PWD/.github/TestConfig.json"
         (dotnet sln list |
-        grep '.Tests.' |
-        grep -v 'Lombiq.Tests.UI.csproj' |
-        grep -v 'Lombiq.Tests.csproj' |
-        sed -e 's/\\/\//g' -e '$atrue' -e 's/\(.*\)/echo "::group::\1" \&\&\ndotnet test -c Release --no-restore --no-build '"'\\1'"' \&\&\necho "::endgroup::" \&\&/' |
-        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
+            grep '.Tests.' |
+            grep -v 'Lombiq.Tests.UI.csproj' |
+            grep -v 'Lombiq.Tests.csproj' |
+            sed -e 's/\\/\//g' \
+                -e '$atrue' \
+                -e 's/\(.*\)/echo "::group::\1" \&\&\ndotnet test -c Release --no-restore --no-build '"'\\1'"' \&\&\necho "::endgroup::" \&\&/' |
+            bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) |
+            grep -v '^Connection refused \[::ffff:127.0.0.1\]';
         grep SUCCESS .ui_test_result
     - uses: actions/upload-artifact@v2
       if: failure()
